htmlSrcDir:    src/html/
scssSrcDir:    src/sass/
jsSrcDir:      src/js/
imagesSrcDir:  src/images/
scssBuildDir:  build/sass/
jsBuildDir:    build/js/
htmlDistDir:   dist/html/
cssDistDir:    dist/css/
jsDistDir:     dist/js/
imagesDistDir: dist/images/
